version: 0.2

phases:
  install:
    commands:
      - echo Build Started on `date`

  build:
    commands:
      - echo Pushing Docker image...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - docker build -t $REPO .
      - docker tag $REPO:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO:latest
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
